Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using RinkuHRApp.Filters;
using RinkuHRApp.Models;
using RinkuHRApp.Services;

namespace RinkuHRApp.Controllers;

[CheckSelectedPayrollAtribute]
public class EmployeeController : Controller
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private ISession _session => _httpContextAccessor.HttpContext.Session;
    private readonly ILogger<EmployeeController> _logger;
    
    private readonly IEmployeeService _employeeService;
    private readonly IPositionService _positionService;
    private readonly PayrollSelectionViewModel _selectedPayroll;

    public EmployeeController(
        IHttpContextAccessor httpContextAccessor,
        ILogger<EmployeeController> logger,
        IEmployeeService employeeService,
        IPositionService positionService,
        IPayrollService payrollService
        )
    {
        _httpContextAccessor = httpContextAccessor;
        _logger = logger;
        _employeeService = employeeService;
        _positionService = positionService;
        _selectedPayroll =  _employeeService.FromJSONStringToObject<PayrollSelectionViewModel>(
            _session.GetString("SelectedPayroll")
        );
    }

    [HttpGet]
    public IActionResult Index()
    {
        GetCatalogsToView();
        return View(new EmployeeViewModel(){                // Creates a default object to the view
            SalaryPerHour = 30,
            HoursPerDay = 8,
            DaysPerWeek = 6,
            PayrollId = _selectedPayroll.PayrollId,
            StatusId = true
        });
    }

    // Search a employee by ID
    [HttpGet]
    public IActionResult SearchEmployee(int id)
    {
        EmployeeViewModel employee = _employeeService.GetOne(id);
        GetCatalogsToView("EditEmployee");

        return View("Index", employee);
    }

    [HttpPost]
    public IActionResult NewEmployee(EmployeeViewModel model)
    {
        if(ModelState.IsValid) {
            _employeeService.AddNew(model);
            TempData["Done"] = "Empleado agregado exitosamente";

            return RedirectToAction("Index");
        }

        GetCatalogsToView();
        return View("Index", model);
    }

    [HttpPost]
    public IActionResult EditEmployee(EmployeeViewModel model)
    {
        if(ModelState.IsValid) {
            _employeeService.Edit(model);
            TempData["Done"] = "Empleado actualizado exitosamente";
            
            return RedirectToAction("Index");
        }
        
        GetCatalogsToView("EditEmployee");
        return View("Index", model);
    }
    
    // This method is used to avoid repetitive data
    private void GetCatalogsToView(string action = "NewEmployee")
    {
        ViewBag.Positions = _positionService.GetAll();                                  // Retrieve data from the positon catalog
        ViewBag.Employees = _employeeService.GetAll(_selectedPayroll.PayrollId);        // Retrieve data from the employee catalog by payroll
        ViewBag.Action = action;                                                        // It is the form action
        TempData["PayrollLabel"] = _selectedPayroll.Payroll;
    }
}

Controllers/PayrollController.cs
using Microsoft.AspNetCore.Mvc;
using RinkuHRApp.Filters;
using RinkuHRApp.Models;
using RinkuHRApp.Services;

namespace RinkuHRApp.Controllers;

[CheckSelectedPayrollAtribute]
public class PayrollController : Controller
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private ISession _session => _httpContextAccessor.HttpContext.Session;
    private readonly ILogger<PayrollController> _logger;

    private readonly IPayrollService _payrollService;
    private readonly IEmployeeService _employeeService;
    private readonly PayrollSelectionViewModel _selectedPayroll;

    public PayrollController(
        IHttpContextAccessor httpContextAccessor,
        ILogger<PayrollController> logger,
        IPayrollService payrollService,
        IEmployeeService employeeService
    )
    {
        _httpContextAccessor = httpContextAccessor;
        _logger = logger;
        _payrollService = payrollService;
        _employeeService = employeeService;
        _selectedPayroll =  _employeeService.FromJSONStringToObject<PayrollSelectionViewModel>(
        _session.GetString("SelectedPayroll")
        );
    }

    [HttpGet]
    public IActionResult Index()
    {
        ViewBag.Employees = _employeeService.GetAllActives(_selectedPayroll.PayrollId);     // Retrieve data from the active employee catalog by payroll
        ViewBag.PayrollConcepts = _payrollService.GetPayrollConcepts(                       // Retrieve data from the calculated payroll by period
            _selectedPayroll.PayrollId,
            _selectedPayroll.PeriodId
        );
        TempData["PayrollLabel"] = _selectedPayroll.Payroll;

        return View();
    }

    // This method calls the main process to calculate payroll
    [HttpPost]
    public IActionResult Index(string employeeId)
    {
        TempData["rowsAffected"] = _payrollService.RunPayroll(_selectedPayroll.PayrollId, _selectedPayroll.PeriodId, employeeId);
                
        return RedirectToAction("Index");
    }
}

Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using RinkuHRApp.Filters;
using RinkuHRApp.Models;
using RinkuHRApp.Services;

namespace RinkuHRApp.Controllers;

[CheckSelectedPayrollAtribute]
public class TransactionController : Controller
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private ISession _session => _httpContextAccessor.HttpContext.Session;
    private readonly ILogger<TransactionController> _logger;
        
    private readonly IEmployeeService _employeeService;
    private readonly ITransactionService _transactionService;
    private readonly PayrollSelectionViewModel _selectedPayroll;

    public TransactionController(
        IHttpContextAccessor httpContextAccessor,
        ILogger<TransactionController> logger,
        IEmployeeService employeeService,
        ITransactionService transactionService
    )
    {
        _httpContextAccessor = httpContextAccessor;
        _logger = logger;
        _employeeService = employeeService;
        _transactionService = transactionService;
       _selectedPayroll =  _employeeService.FromJSONStringToObject<PayrollSelectionViewModel>(
            _session.GetString("SelectedPayroll")
        );
    }

    [HttpGet]
    public IActionResult Index()
    {
        GetCatalogsToView();
        return View(new TransactionViewModel(){                 // Creates a default object to the view
            PayrollId = _selectedPayroll.PayrollId,
            PeriodId = _selectedPayroll.PeriodId,
            ConceptId = 2,
            Amount = 5.00M
        });
    }

    // Search a transaction capture by IDs
    [HttpGet]
    public IActionResult SearchTransaction(int payrollId, int periodId, int conceptId, int employeeId, int sequence)
    {
        TransactionViewModel transaction = _transactionService.GetOne(payrollId, periodId, conceptId, employeeId, sequence);
        GetCatalogsToView("EditTransaction");
            
        return View("Index", transaction);
    }

    [HttpPost]
    public IActionResult NewTransaction(TransactionViewModel model)
    {
        if(ModelState.IsValid) {
            _transactionService.AddNew(model);
            TempData["Done"] = "Bono agregado exitosamente";

            return RedirectToAction("Index");
        }

        GetCatalogsToView();
        return View("Index", model);
    }

    [HttpPost]
    public IActionResult EditTransaction(TransactionViewModel model)
    {
        if(ModelState.IsValid) {
            _transactionService.Edit(model);
            TempData["Done"] = "Bono actualizado exitosamente";
                
            return RedirectToAction("Index");
        }

        GetCatalogsToView("EditTransaction");
        return View("Index", model);
    }

    // This method is used to avoid repetitive data
    private void GetCatalogsToView(string action =  "NewTransaction")
    {
        IEnumerable<EmployeeViewModel> employees = _employeeService.GetAllActives(_selectedPayroll.PayrollId);              // Retrieve data from the employee catalog by payroll
        ViewBag.Employees = employees;
        ViewBag.EmployeesStr = _employeeService.ToJSONString<IEnumerable<EmployeeViewModel>>(employees);                    // The retrieve data is converted in string to be used to the view
        ViewBag.Transactions = _transactionService.GetAllActives(_selectedPayroll.PayrollId, _selectedPayroll.PeriodId);    // retrieves data from active transaction captures
        ViewBag.Action = action;                                                                                            // It is the form action
        TempData["PayrollLabel"] = _selectedPayroll.Payroll;
    }
    }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-MX">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RinkuHRApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RinkuHRApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Index">Rinku Human Resorces App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Movimientos/Pago</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payroll" asp-action="Index">Nómina</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PayrollSelect">
                                <b>@TempData["PayrollLabel"]</b>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RinkuHRApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>